markdown: kramdown
baseurl: /citysdk-ld

prose:
  ignore:
    - .gitignore
    - /\..*
    - /_config.yml
    - /LICENSE.md
    - /README.md
    - /js
    - /css
    - /layouts
  metadata:
    _posts:
	  - name: "layout"
	    field:
		  element: "text"
		  help: "select required layout" 