markdown: kramdown
baseurl: /citysdk-ld

prose:
  ignore:
    - .gitignore
    - /\..*
    - /_config.yml
    - /LICENSE.md
    - /README.md
    - /js
    - /css
    - /layouts

  metadata:
    "":
      - name: "layout"
        field:
          element: "text"
          value: ""
          help: "choose one from home (home only), default (2 columns), single (1 column), map (viewer only)"
      - name: "title"
        field:
          element: "text"
          value: ""
      - name: "mainmenu"
        field:
          element: "text"
          value: ""

