source "https://rubygems.org"

ruby '1.9.3'

gem "sinatra", :require => "sinatra/base"
gem 'redcarpet'

group :development do
  gem 'capistrano', '~>2.14.1'
  gem 'capistrano-ext', '~>1.2.1'
  gem 'passenger', '~>4.0.23'
end


