source 'https://rubygems.org'

ruby '1.9.3'

gem 'active_support'
gem 'amatch'
gem 'base62'
gem 'dalli' # Memcache
gem 'faraday'
gem 'i18n', '~>0.6.4'
gem 'logger'
gem 'pg'
gem 'racksh'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'sequel'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-sequel'
gem 'stringex'
gem 'yajl-ruby'

group :development do
  gem 'capistrano', '~>2.14.1'
  gem 'capistrano-ext', '~>1.2.1'
  gem 'passenger', '~>4.0.23'
end

